"""
Comprehensive diagnostic for page ID: 59d2db58-574b-4189-8b0d-a50cb1e4b4b2
Published at: /cc
"""
import requests
import json

print("=" * 70)
print("DIAGNOSTIC REPORT: Filter Options Issue")
print("=" * 70)

# Step 1: Get page from Builder API
print("\n[1] Fetching page from Builder API...")
builder_url = f"http://127.0.0.1:8000/api/pages/59d2db58-574b-4189-8b0d-a50cb1e4b4b2"
response = requests.get(builder_url)

if response.status_code != 200:
    print(f"❌ FAILED: {response.status_code}")
    print(response.text)
    exit(1)

page = response.json()['data']
print(f"✅ Page found: {page['name']} (slug: {page['slug']})")

# Step 2: Find DataTable in layout
print("\n[2] Searching for DataTable component...")
layout = page.get('layoutData', {})
components = layout.get('content', [])

def find_datatables(comps, path=""):
    """Recursively find all DataTable components"""
    tables = []
    for i, comp in enumerate(comps):
        comp_path = f"{path}[{i}]"
        comp_type = comp.get('type', '')
        if comp_type in ('DataTable', 'datatable'):  # Support both cases
            tables.append((comp_path, comp))
        if 'children' in comp and comp['children']:
            tables.extend(find_datatables(comp['children'], f"{comp_path}.children"))
    return tables

datatables = find_datatables(components)

if not datatables:
    print("❌ PROBLEM 1: No DataTable found in page layout")
    print("   This might mean the component type is misnamed or structure changed")
    exit(1)

print(f"✅ Found {len(datatables)} DataTable(s)")

# Step 3: Check each DataTable for filters and optionsDataRequest
problems = []

for path, dt in datatables:
    print(f"\n[3] Analyzing DataTable at {path}...")
    
    # Get binding
    binding = dt.get('binding')
    if not binding:
        binding = dt.get('props', {}).get('binding')
    
    if not binding:
        problems.append(f"DataTable at {path}: No binding found")
        print(f"   ❌ PROBLEM: No binding")
        continue
    
    print(f"   ✅ Has binding")
    
    # Check datasourceId
    ds_id = binding.get('datasourceId')
    print(f"   Datasource ID: {ds_id or 'MISSING'}")
    if not ds_id:
        problems.append(f"DataTable at {path}: Missing datasourceId in binding")
    
    # Check frontendFilters
    filters = binding.get('frontendFilters', [])
    print(f"   Frontend Filters: {len(filters)}")
    
    if not filters:
        print(f"   ⚠️  No frontend filters configured")
        continue
    
    # Analyze each filter
    for i, f in enumerate(filters):
        col = f.get('column')
        ftype = f.get('filterType')
        label = f.get('label', col)
        
        print(f"\n   Filter {i+1}: {label} ({ftype})")
        print(f"      Column: {col}")
        
        # Check if this filter type should have options
        if ftype in ('dropdown', 'multiselect'):
            if 'optionsDataRequest' in f:
                print(f"      ✅ Has optionsDataRequest")
                req = f['optionsDataRequest']
                print(f"         URL: {req.get('url', 'N/A')}")
                print(f"         Body: {req.get('body', {})}")
            else:
                problem = f"DataTable at {path}, Filter '{label}': Missing optionsDataRequest (type={ftype})"
                problems.append(problem)
                print(f"      ❌ MISSING optionsDataRequest")
                print(f"         This is a {ftype} filter and SHOULD have it!")
        else:
            print(f"      ℹ️  No optionsDataRequest needed for {ftype} type")

# Step 4: Summary
print("\n" + "=" * 70)
print("SUMMARY")
print("=" * 70)

if problems:
    print(f"\n🔴 Found {len(problems)} PROBLEM(S):\n")
    for i, p in enumerate(problems, 1):
        print(f"{i}. {p}")
    
    print("\n" + "=" * 70)
    print("ROOT CAUSE ANALYSIS")
    print("=" * 70)
    
    if any("Missing optionsDataRequest" in p for p in problems):
        print("\n❌ Filter options are NOT being generated by FastAPI")
        print("\nPossible causes:")
        print("  1. Page was published BEFORE the optionsDataRequest logic was added")
        print("  2. The datasource list is empty when convert_component runs")
        print("  3. The filter configuration is malformed")
        print("  4. FastAPI's convert_component isn't being called during publish")
        
    if any("Missing datasourceId" in p for p in problems):
        print("\n❌ DataTable binding lacks a datasource ID")
        print("     → This causes fallback to first available datasource")
        print("     → Might work in single-datasource setups but unreliable")
else:
    print("\n✅ NO PROBLEMS FOUND")
    print("   All filters have optionsDataRequest where expected")
    print("\n   If filters still don't work in browser:")
    print("   - Check browser console for JavaScript errors")
    print("   - Check that DataTable.tsx useEffect is running")
    print("   - Verify /api/data/execute endpoint is reachable")
