import re
content = open('alembic/versions/1107e0ddc6fa_add_project_id_to_multi_tenant_models.py').read()

upgrade_code = '''def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation_executions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'])

    with op.batch_alter_table('edge_providers_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'])

    with op.batch_alter_table('edge_queues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###'''

downgrade_code = '''def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edge_queues', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('edge_providers_accounts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('automation_executions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('project_id')
    # ### end Alembic commands ###'''

content = re.sub(r'(?ms)def upgrade\(\) -> None:.*?# ### end Alembic commands ###', upgrade_code, content)
content = re.sub(r'(?ms)def downgrade\(\) -> None:.*?# ### end Alembic commands ###', downgrade_code, content)

open('alembic/versions/1107e0ddc6fa_add_project_id_to_multi_tenant_models.py', 'w').write(content)

