"""Add project_id to multi-tenant models

Revision ID: 1107e0ddc6fa
Revises: 3ff5da2b43e2
Create Date: 2026-04-18 02:16:25.073472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '1107e0ddc6fa'
down_revision: Union[str, Sequence[str], None] = '3ff5da2b43e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation_executions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_automation_executions_project_id', 'project', ['project_id'], ['id'])

    with op.batch_alter_table('edge_providers_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_edge_providers_accounts_project_id', 'project', ['project_id'], ['id'])

    with op.batch_alter_table('edge_queues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_edge_queues_project_id', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### end Alembic commands ###
