"""Initial migration with TableSchemaCache improvements

Revision ID: c5311426ba79
Revises: 
Create Date: 2026-01-06 09:35:35.486210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'c5311426ba79'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SAFETY: Commented out drop_table commands for tables that exist in DB but not yet in Models
    # op.drop_table('page_views')
    # op.drop_table('datasources')
    # op.drop_table('rls_policy_metadata')
    # op.drop_table('project_settings')
    # op.drop_table('auth_forms')
    # op.drop_table('assets')
    with op.batch_alter_table('app_variables', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('value',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('formula',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sync_job_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('record_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('conflict_type', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('conflict_data', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('resolution_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('resolution_data', sa.Text(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'sync_jobs', ['sync_job_id'], ['id'])
        batch_op.drop_column('job_id')
        batch_op.drop_column('status')
        batch_op.drop_column('record_key')
        batch_op.drop_column('slave_data')
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('conflicting_fields')
        batch_op.drop_column('resolved_data')
        batch_op.drop_column('resolution_notes')
        batch_op.drop_column('resolved_by')
        batch_op.drop_column('master_data')
        batch_op.drop_column('sync_config_id')

    with op.batch_alter_table('datasource_views', schema=None) as batch_op:
        batch_op.add_column(sa.Column('view_definition', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('is_shared', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.String(), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('linked_views')
        batch_op.drop_column('column_order')
        batch_op.drop_column('filters')
        batch_op.drop_column('visible_columns')
        batch_op.drop_column('webhooks')
        batch_op.drop_column('target_table')
        batch_op.drop_column('field_mappings')
        batch_op.drop_column('pinned_columns')
        batch_op.drop_column('description')

    with op.batch_alter_table('field_mappings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_table', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('source_field', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('target_table', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('target_field', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('transformation_rules', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('data_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.String(), nullable=False))
        batch_op.drop_column('master_column')
        batch_op.drop_column('skip_sync')
        batch_op.drop_column('transform')
        batch_op.drop_column('is_key_field')
        batch_op.drop_column('slave_column')

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('slug',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('keywords',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('deleted_at',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('supabase_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('supabase_anon_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('supabase_service_key_encrypted',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('sync_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_datasource_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('target_datasource_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('config_data', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('sync_frequency', sa.String(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_sync_at')
        batch_op.drop_column('slave_table')
        batch_op.drop_column('master_datasource_id')
        batch_op.drop_column('cron_schedule')
        batch_op.drop_column('slave_pk_column')
        batch_op.drop_column('slave_view_id')
        batch_op.drop_column('master_view_id')
        batch_op.drop_column('description')
        batch_op.drop_column('master_pk_column')
        batch_op.drop_column('slave_datasource_id')
        batch_op.drop_column('sync_deletes')
        batch_op.drop_column('master_table')
        batch_op.drop_column('batch_size')
        batch_op.drop_column('webhook_url')
        batch_op.drop_column('conflict_strategy')

    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('records_processed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('records_failed', sa.Integer(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
        batch_op.alter_column('started_at',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('completed_at',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_column('triggered_by')
        batch_op.drop_column('total_records')
        batch_op.drop_column('error_count')
        batch_op.drop_column('conflict_count')
        batch_op.drop_column('updated_records')
        batch_op.drop_column('inserted_records')
        batch_op.drop_column('processed_records')
        batch_op.drop_column('deleted_records')
        batch_op.drop_column('error_details')

    # RE-GENERATED "SAFE" BLOCK FOR table_schema_cache based on user requirements:
    # 1. Add columns/foreign_keys
    # 2. Add schema_data/last_updated if missing (Model has them)
    
    # -- Manual "Clean" Migration Content Follows --
    
    # 1. Update table_schema_cache (The critical fix)
    with op.batch_alter_table('table_schema_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schema_data', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('last_updated', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('is_valid', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('columns', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('foreign_keys', sa.Text(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_datasource_table'), type_='unique')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fetched_at')

    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('session_token',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('expires_at',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('created_at')

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('supabase_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('supabase_anon_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.TEXT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('supabase_anon_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('supabase_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.TEXT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('expires_at',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('session_token',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('table_schema_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fetched_at', sa.DATETIME(), nullable=False))
        batch_op.create_foreign_key(None, 'datasources', ['datasource_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('uq_datasource_table'), ['datasource_id', 'table_name'])
        batch_op.alter_column('foreign_keys',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('columns',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               nullable=False)
        batch_op.drop_column('is_valid')
        batch_op.drop_column('last_updated')
        batch_op.drop_column('schema_data')
        batch_op.drop_column('foreign_keys')
        batch_op.drop_column('columns')

    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error_details', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('deleted_records', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('processed_records', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('inserted_records', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('updated_records', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('conflict_count', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('error_count', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('total_records', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('triggered_by', sa.VARCHAR(length=50), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('completed_at',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('started_at',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
        batch_op.drop_column('records_failed')
        batch_op.drop_column('records_processed')

    with op.batch_alter_table('sync_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conflict_strategy', sa.VARCHAR(length=11), nullable=False))
        batch_op.add_column(sa.Column('webhook_url', sa.VARCHAR(length=512), nullable=True))
        batch_op.add_column(sa.Column('batch_size', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('master_table', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('sync_deletes', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('slave_datasource_id', sa.VARCHAR(length=36), nullable=False))
        batch_op.add_column(sa.Column('master_pk_column', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('master_view_id', sa.VARCHAR(length=36), nullable=True))
        batch_op.add_column(sa.Column('slave_view_id', sa.VARCHAR(length=36), nullable=True))
        batch_op.add_column(sa.Column('slave_pk_column', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('cron_schedule', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('master_datasource_id', sa.VARCHAR(length=36), nullable=False))
        batch_op.add_column(sa.Column('slave_table', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('last_sync_at', sa.DATETIME(), nullable=True))
        batch_op.create_foreign_key(None, 'datasource_views', ['slave_view_id'], ['id'])
        batch_op.create_foreign_key(None, 'datasources', ['master_datasource_id'], ['id'])
        batch_op.create_foreign_key(None, 'datasources', ['slave_datasource_id'], ['id'])
        batch_op.create_foreign_key(None, 'datasource_views', ['master_view_id'], ['id'])
        batch_op.alter_column('updated_at',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('sync_frequency')
        batch_op.drop_column('config_data')
        batch_op.drop_column('target_datasource_id')
        batch_op.drop_column('source_datasource_id')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('supabase_service_key_encrypted',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('supabase_anon_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('supabase_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('deleted_at',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('keywords',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('slug',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('field_mappings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slave_column', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('is_key_field', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('transform', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('skip_sync', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('master_column', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('created_at')
        batch_op.drop_column('data_type')
        batch_op.drop_column('transformation_rules')
        batch_op.drop_column('target_field')
        batch_op.drop_column('target_table')
        batch_op.drop_column('source_field')
        batch_op.drop_column('source_table')

    with op.batch_alter_table('datasource_views', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('pinned_columns', sqlite.JSON(), nullable=False))
        batch_op.add_column(sa.Column('field_mappings', sqlite.JSON(), nullable=False))
        batch_op.add_column(sa.Column('target_table', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('webhooks', sqlite.JSON(), nullable=False))
        batch_op.add_column(sa.Column('visible_columns', sqlite.JSON(), nullable=False))
        batch_op.add_column(sa.Column('filters', sqlite.JSON(), nullable=False))
        batch_op.add_column(sa.Column('column_order', sqlite.JSON(), nullable=False))
        batch_op.add_column(sa.Column('linked_views', sqlite.JSON(), nullable=False))
        batch_op.create_foreign_key(None, 'datasources', ['datasource_id'], ['id'])
        batch_op.alter_column('updated_at',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('created_by')
        batch_op.drop_column('is_shared')
        batch_op.drop_column('view_definition')

    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sync_config_id', sa.VARCHAR(length=36), nullable=False))
        batch_op.add_column(sa.Column('master_data', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('resolved_by', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('resolution_notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('resolved_data', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('conflicting_fields', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('resolved_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('slave_data', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('record_key', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=16), nullable=False))
        batch_op.add_column(sa.Column('job_id', sa.VARCHAR(length=36), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'sync_jobs', ['job_id'], ['id'])
        batch_op.create_foreign_key(None, 'sync_configs', ['sync_config_id'], ['id'])
        batch_op.alter_column('created_at',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.drop_column('resolution_data')
        batch_op.drop_column('resolution_status')
        batch_op.drop_column('conflict_data')
        batch_op.drop_column('conflict_type')
        batch_op.drop_column('record_id')
        batch_op.drop_column('sync_job_id')

    with op.batch_alter_table('app_variables', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('formula',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('value',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)

    op.create_table('assets',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('filename', sa.TEXT(), nullable=False),
    sa.Column('original_name', sa.TEXT(), nullable=False),
    sa.Column('mime_type', sa.TEXT(), nullable=False),
    sa.Column('size', sa.INTEGER(), nullable=False),
    sa.Column('file_path', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_forms',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('type', sa.TEXT(), nullable=False),
    sa.Column('config', sa.TEXT(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('target_contact_type', sa.TEXT(), nullable=True),
    sa.Column('allowed_contact_types', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('redirect_url', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('created_at', sa.NullType(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('updated_at', sa.NullType(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.CheckConstraint("type IN ('login', 'signup', 'both')"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_settings',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('redis_url', sa.VARCHAR(length=512), nullable=True),
    sa.Column('redis_enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('cache_ttl_data', sa.INTEGER(), nullable=False),
    sa.Column('cache_ttl_count', sa.INTEGER(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rls_policy_metadata',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('table_name', sa.TEXT(), nullable=False),
    sa.Column('policy_name', sa.TEXT(), nullable=False),
    sa.Column('form_data', sa.TEXT(), nullable=False),
    sa.Column('generated_using', sa.TEXT(), nullable=True),
    sa.Column('generated_check', sa.TEXT(), nullable=True),
    sa.Column('sql_hash', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.NullType(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('updated_at', sa.NullType(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_name', 'policy_name')
    )
    op.create_table('datasources',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('type', sa.VARCHAR(length=17), nullable=False),
    sa.Column('host', sa.VARCHAR(length=255), nullable=True),
    sa.Column('port', sa.INTEGER(), nullable=True),
    sa.Column('database', sa.VARCHAR(length=255), nullable=True),
    sa.Column('username', sa.VARCHAR(length=255), nullable=True),
    sa.Column('password_encrypted', sa.TEXT(), nullable=True),
    sa.Column('extra_config', sa.TEXT(), nullable=True),
    sa.Column('api_url', sa.VARCHAR(length=512), nullable=True),
    sa.Column('api_key_encrypted', sa.TEXT(), nullable=True),
    sa.Column('table_prefix', sa.VARCHAR(length=50), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('last_tested_at', sa.DATETIME(), nullable=True),
    sa.Column('last_test_success', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('anon_key_encrypted', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('page_views',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('page_id', sa.TEXT(), nullable=False),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.Column('ip_address', sa.TEXT(), nullable=True),
    sa.Column('referrer', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
